[package]
name = "trascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
hashmap = "0.0.1"
uuid = "1.3.3"
